# Generated by Django 3.2.9 on 2021-11-09 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='sources',
            field=models.ManyToManyField(blank=True, to='private.Source'),
        ),
    ]
