# Generated by Django 3.2.9 on 2021-11-09 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0002_alter_person_sources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativename',
            name='alternate_first',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='alternativename',
            name='alternate_surname',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='alternativename',
            name='end_date_of_alternative',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='alternativename',
            name='explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='alternativename',
            name='sources',
            field=models.ManyToManyField(blank=True, to='private.Source'),
        ),
        migrations.AlterField(
            model_name='alternativename',
            name='start_date_of_alternative',
            field=models.DateTimeField(blank=True),
        ),
    ]
