# Generated by Django 3.2.9 on 2021-11-09 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0003_auto_20211109_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativename',
            name='start_date_of_alternative',
            field=models.DateField(blank=True),
        ),
    ]
