# Generated by Django 3.2.9 on 2021-11-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0004_alter_alternativename_start_date_of_alternative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativename',
            name='end_date_of_alternative',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='alternativename',
            name='start_date_of_alternative',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
