# Generated by Django 3.2.9 on 2021-11-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0005_auto_20211110_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativename',
            name='end_date_of_alternative',
            field=models.CharField(blank=True, help_text="YYYY-MM-DD. Approximate dates can also be given in YYYY-MM or YYYY format. In this case, tick the below 'Start | End date approximate' box.", max_length=255),
        ),
        migrations.AlterField(
            model_name='alternativename',
            name='start_date_of_alternative',
            field=models.CharField(blank=True, help_text="YYYY-MM-DD. Approximate dates can also be given in YYYY-MM or YYYY format. In this case, tick the below 'Start | End date approximate' box.", max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.CharField(blank=True, help_text="YYYY-MM-DD. Approximate dates can also be given in YYYY-MM or YYYY format. In this case, tick the below 'Start | End date approximate' box.", max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.CharField(blank=True, help_text='Indicate places from non-specifiic to specific as possible from left to right. Country --> state/province --> municipality --> city/town --> address. E.g. USA, Rhode Island, Providence, 105 North Main st.', max_length=1020),
        ),
        migrations.AlterField(
            model_name='event',
            name='sources',
            field=models.ManyToManyField(blank=True, to='private.Source'),
        ),
    ]
