# Generated by Django 3.2.9 on 2021-12-08 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('private', '0005_alter_source_source_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativename',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alternativename',
            name='principle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='private.person'),
        ),
        migrations.AlterField(
            model_name='biographicalinfonugget',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='epoch',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='person',
            name='created_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='person',
            name='headshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='headhshot', to='private.source'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='bidirrel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='private.relationship'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='principle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='principle', to='private.person'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='referent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referent', to='private.person'),
        ),
        migrations.AlterField(
            model_name='research',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='research',
            name='principle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='private.person'),
        ),
        migrations.AlterField(
            model_name='researchreply',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='researchreply',
            name='reply_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='private.research'),
        ),
        migrations.AlterField(
            model_name='source',
            name='created_in_DB_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
