# Generated by Django 3.2.9 on 2021-11-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0006_auto_20211110_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_description',
            field=models.TextField(blank=True),
        ),
    ]
