# Generated by Django 3.2.9 on 2021-11-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0007_alter_event_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epoch',
            name='end_date',
            field=models.CharField(blank=True, help_text="YYYY-MM-DD. Approximate dates can also be given in YYYY-MM or YYYY format. In this case, tick the below 'Start | End date approximate' box.", max_length=255),
        ),
        migrations.AlterField(
            model_name='epoch',
            name='sources',
            field=models.ManyToManyField(blank=True, to='private.Source'),
        ),
        migrations.AlterField(
            model_name='epoch',
            name='start_date',
            field=models.CharField(blank=True, help_text="YYYY-MM-DD. Approximate dates can also be given in YYYY-MM or YYYY format. In this case, tick the below 'Start | End date approximate' box.", max_length=255),
        ),
    ]
