# Generated by Django 3.2.9 on 2021-11-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0008_auto_20211110_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epoch',
            name='epoch_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='epoch',
            name='epoch_type',
            field=models.CharField(choices=[('residence', 'residence'), ('study / work', 'study / work'), ('marriage', 'marriage'), ('other', 'other')], max_length=255),
        ),
    ]
