# Generated by Django 3.2.9 on 2021-11-10 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0010_auto_20211110_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relationship',
            old_name='source',
            new_name='sources',
        ),
    ]
