# Generated by Django 3.2.9 on 2021-11-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0011_rename_source_relationship_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='biographicalinfonugget',
            name='end_date',
            field=models.CharField(blank=True, help_text="YYYY-MM-DD. Approximate dates can also be given in YYYY-MM or YYYY format. In this case, tick the below 'Start | End date approximate' box.", max_length=255),
        ),
        migrations.AddField(
            model_name='biographicalinfonugget',
            name='end_date_approximate',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biographicalinfonugget',
            name='start_date',
            field=models.CharField(blank=True, help_text="YYYY-MM-DD. Approximate dates can also be given in YYYY-MM or YYYY format. In this case, tick the below 'Start | End date approximate' box.", max_length=255),
        ),
        migrations.AddField(
            model_name='biographicalinfonugget',
            name='start_date_approximate',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='biographicalinfonugget',
            name='sources',
            field=models.ManyToManyField(blank=True, to='private.Source'),
        ),
    ]
