# Generated by Django 3.2.9 on 2021-11-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0012_auto_20211110_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='source_bibliographic_reference',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_date_of_creation',
            field=models.CharField(blank=True, help_text="YYYY-MM-DD. Approximate dates can also be given in YYYY-MM or YYYY format. In this case, tick the below 'Start | End date approximate' box.", max_length=255),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_file',
            field=models.FileField(upload_to=''),
        ),
    ]
