# Generated by Django 3.2.9 on 2021-11-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0013_auto_20211110_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='source_creator',
            field=models.CharField(blank=True, max_length=510),
        ),
    ]
