# Generated by Django 3.2.9 on 2021-11-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0014_alter_source_source_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='sex',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=255),
            preserve_default=False,
        ),
    ]
