# Generated by Django 3.2.9 on 2021-11-10 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0015_person_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='living',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
