# Generated by Django 3.2.9 on 2021-11-12 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0017_research_researchreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='headshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='headhshot', to='private.source'),
        ),
        migrations.AlterField(
            model_name='person',
            name='sources',
            field=models.ManyToManyField(blank=True, related_name='sources', to='private.Source'),
        ),
    ]
