# Generated by Django 3.2.9 on 2021-11-19 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0018_auto_20211112_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='bidirrel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='private.relationship'),
        ),
    ]
